{
	"version": 1543265469,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/sprite-sheet0.png",
		"images/player-sheet0.png",
		"images/tilemap.png",
		"images/thorn-sheet0.png",
		"images/thorn-sheet1.png",
		"images/astronaut-sheet0.png",
		"images/astronaut-sheet1.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/flag-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/fire-sheet0.png",
		"images/tiledbackground2.png",
		"images/box_start-sheet0.png",
		"images/box_tutorial-sheet0.png",
		"images/box_credits-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/screen_congratulations-sheet0.png",
		"images/laser-sheet0.png",
		"images/screen_credits-sheet0.png",
		"images/arrow-sheet0.png",
		"images/screen_tutorial-sheet0.png",
		"images/tilemap2.png",
		"images/tiledbackground4.png",
		"images/sprite29-sheet0.png",
		"images/sprite30-sheet0.png",
		"images/drill-sheet0.png",
		"images/explosion-sheet0.png",
		"images/explosion-sheet1.png",
		"images/explosion-sheet2.png",
		"images/camerafollow-sheet0.png",
		"images/sprite2-sheet0.png",
		"media/drill.m4a",
		"media/drill.ogg",
		"media/intro_music.m4a",
		"media/intro_music.ogg",
		"media/jump_sound.m4a",
		"media/jump_sound.ogg",
		"media/laser_sound.m4a",
		"media/laser_sound.ogg",
		"media/fase1_music.m4a",
		"media/fase1_music.ogg",
		"media/walk_sound.m4a",
		"media/walk_sound.ogg",
		"media/click_sound.ogg",
		"media/death_sound.m4a",
		"media/death_sound.ogg",
		"media/sound 1 (longe).m4a",
		"media/sound 1 (longe).ogg",
		"media/sound 2 (médio).m4a",
		"media/sound 2 (médio).ogg",
		"media/sound 3 (perto).m4a",
		"media/sound 4 (muito perto).m4a",
		"media/sound 4 (muito perto).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}